@extends('layouts.app')

@section('title', 'Amandemen | SIMASADI')

@section('content')
<div class="page-heading"><div><h1>Pengajuan amandemen</h1><p class="lede">Pantau pengajuan perubahan sertifikat atau lampiran akreditasi.</p></div><a class="button primary" href="{{ route('amendments.create') }}"><x-icon name="plus" size="16" /><span>Catat pengajuan</span></a></div>
<section class="panel">
    <form class="table-filters" method="GET">
        <div class="table-filter-grid"><label>Nomor pengajuan<input name="search" value="{{ $search }}" placeholder="Nomor pengajuan"></label><label>LPK<select name="lpk_id"><option value="">Semua LPK</option>@foreach($lpks as $lpk)<option value="{{ $lpk->id }}" @selected($lpkId === $lpk->id)>{{ $lpk->name }}</option>@endforeach</select></label><label>Jenis<select name="amendment_type"><option value="">Semua jenis</option>@foreach($amendmentTypes as $type)<option value="{{ $type }}" @selected($amendmentType === $type)>{{ $type }}</option>@endforeach</select></label><label>Status<select name="status"><option value="">Semua status</option>@foreach(['SUBMITTED' => 'Diajukan', 'UNDER_REVIEW' => 'Ditinjau', 'NEED_REVISION' => 'Perlu revisi', 'APPROVED' => 'Disetujui', 'REJECTED' => 'Ditolak', 'COMPLETED' => 'Selesai'] as $value => $label)<option value="{{ $value }}" @selected($status === $value)>{{ $label }}</option>@endforeach</select></label><label>Diajukan dari<input type="date" name="submitted_from" value="{{ $submittedFrom }}"></label><label>Diajukan sampai<input type="date" name="submitted_to" value="{{ $submittedTo }}"></label><label>Target dari<input type="date" name="target_from" value="{{ $targetFrom }}"></label><label>Target sampai<input type="date" name="target_to" value="{{ $targetTo }}"></label></div>
        <div class="table-filter-actions"><button class="button secondary" type="submit">Terapkan filter</button>@if($search || $lpkId || $amendmentType || $status || $submittedFrom || $submittedTo || $targetFrom || $targetTo)<a class="button ghost" href="{{ route('amendments.index') }}">Reset</a>@endif</div>
    </form>
    @if($amendments->count())<div class="table-wrap"><table><thead><tr><th>Pengajuan</th><th>LPK</th><th>Jenis</th><th>Status</th><th>Target</th><th></th></tr></thead><tbody>@foreach($amendments as $amendment)<tr><td><strong>{{ $amendment->submission_number }}</strong><span>{{ $amendment->submitted_at->format('d M Y') }}</span></td><td>{{ $amendment->lpk->name }}</td><td>{{ $amendment->amendment_type }}</td><td><x-status :value="$amendment->status" /></td><td>{{ $amendment->target_date?->format('d M Y') ?: 'Tanpa target' }}</td><td><a href="{{ route('amendments.show',$amendment) }}">Detail</a></td></tr>@endforeach</tbody></table></div>{{ $amendments->links() }}@else<div class="empty">{{ $search || $lpkId || $amendmentType || $status || $submittedFrom || $submittedTo || $targetFrom || $targetTo ? 'Tidak ada pengajuan amandemen yang cocok dengan filter.' : 'Belum ada pengajuan amandemen.' }} @if($search || $lpkId || $amendmentType || $status || $submittedFrom || $submittedTo || $targetFrom || $targetTo)<a class="button ghost empty-action" href="{{ route('amendments.index') }}">Reset filter</a>@endif</div>@endif
</section>
@endsection
