@extends('layouts.app')

@section('title', 'Masalah | SIMASADI')

@section('content')
<div class="page-heading"><div><span class="eyebrow">TINDAK LANJUT</span><h1>Laporan masalah</h1><p class="lede">Catat masalah operasional dan ikuti penyelesaiannya.</p></div><a class="button primary" href="{{ route('issues.create') }}">Buat laporan</a></div>
<section class="panel">
    <form class="table-filters" method="GET">
        <div class="table-filter-grid"><label>Cari masalah<input name="search" value="{{ $search }}" placeholder="Judul masalah"></label><label>LPK<select name="lpk_id"><option value="">Semua LPK</option>@foreach($lpks as $lpk)<option value="{{ $lpk->id }}" @selected($lpkId === $lpk->id)>{{ $lpk->name }}</option>@endforeach</select></label><label>Prioritas<select name="priority"><option value="">Semua prioritas</option><option value="HIGH" @selected($priority === 'HIGH')>Tinggi</option><option value="MEDIUM" @selected($priority === 'MEDIUM')>Sedang</option><option value="LOW" @selected($priority === 'LOW')>Rendah</option></select></label><label>Status<select name="status"><option value="">Semua status</option><option value="OPEN" @selected($status === 'OPEN')>Terbuka</option><option value="IN_PROGRESS" @selected($status === 'IN_PROGRESS')>Berjalan</option><option value="RESOLVED" @selected($status === 'RESOLVED')>Selesai</option></select></label><label>Jatuh tempo dari<input type="date" name="due_from" value="{{ $dueFrom }}"></label><label>Jatuh tempo sampai<input type="date" name="due_to" value="{{ $dueTo }}"></label></div>
        <div class="table-filter-actions"><button class="button secondary" type="submit">Terapkan filter</button>@if($search || $lpkId || $priority || $status || $dueFrom || $dueTo)<a class="button ghost" href="{{ route('issues.index') }}">Reset</a>@endif</div>
    </form>
    @if($issues->count())<div class="table-wrap"><table><thead><tr><th>Masalah</th><th>LPK</th><th>Prioritas</th><th>Status</th><th></th></tr></thead><tbody>@foreach($issues as $issue)<tr><td><strong>{{ $issue->title }}</strong><span>{{ $issue->due_date?->format('d M Y') ?: 'Tanpa target' }}</span></td><td>{{ $issue->lpk->name }}</td><td><span class="priority priority-{{ strtolower($issue->priority) }}">{{ ['LOW' => 'Rendah', 'MEDIUM' => 'Sedang', 'HIGH' => 'Tinggi'][$issue->priority] ?? $issue->priority }}</span></td><td><x-status :value="$issue->status" /></td><td><a href="{{ route('issues.show',$issue) }}">Detail</a></td></tr>@endforeach</tbody></table></div>{{ $issues->links() }}@else<div class="empty">{{ $search || $lpkId || $priority || $status || $dueFrom || $dueTo ? 'Tidak ada masalah yang cocok dengan filter.' : 'Belum ada laporan masalah.' }} @if($search || $lpkId || $priority || $status || $dueFrom || $dueTo)<a class="button ghost empty-action" href="{{ route('issues.index') }}">Reset filter</a>@endif</div>@endif
</section>
@endsection
