@extends('layouts.app')

@section('title', 'Program Asesmen | SIMASADI')

@section('content')
<div class="page-heading"><div><h1>Program asesmen</h1><p class="lede">Jadwal dan progres asesmen semua LPK.</p></div><a class="button primary" href="{{ route('assessments.create') }}"><x-icon name="plus" size="16" /><span>Tambah asesmen</span></a></div>
<section class="panel">
    <form class="table-filters" method="GET">
        <div class="table-filter-grid"><label>Cari agenda<input name="search" value="{{ $search }}" placeholder="Judul agenda"></label><label>LPK<select name="lpk_id"><option value="">Semua LPK</option>@foreach($lpks as $lpk)<option value="{{ $lpk->id }}" @selected($lpkId === $lpk->id)>{{ $lpk->name }}</option>@endforeach</select></label><label>Jenis<select name="assessment_type"><option value="">Semua jenis</option>@foreach($assessmentTypes as $type)<option value="{{ $type }}" @selected($assessmentType === $type)>{{ $type }}</option>@endforeach</select></label><label>Status<select name="status"><option value="">Semua status</option>@foreach(['PLANNED' => 'Direncanakan', 'SCHEDULED' => 'Terjadwal', 'IN_PROGRESS' => 'Berjalan', 'COMPLETED' => 'Selesai', 'CANCELLED' => 'Dibatalkan'] as $value => $label)<option value="{{ $value }}" @selected($status === $value)>{{ $label }}</option>@endforeach</select></label><label>Mulai dari<input type="date" name="start_from" value="{{ $startFrom }}"></label><label>Mulai sampai<input type="date" name="start_to" value="{{ $startTo }}"></label></div>
        <div class="table-filter-actions"><button class="button secondary" type="submit">Terapkan filter</button>@if($search || $lpkId || $assessmentType || $status || $startFrom || $startTo)<a class="button ghost" href="{{ route('assessments.index') }}">Reset</a>@endif</div>
    </form>
    @if($assessments->count())<div class="table-wrap"><table><thead><tr><th>Agenda</th><th>LPK</th><th>Waktu</th><th>Biaya Asesor</th><th>Status</th><th></th></tr></thead><tbody>@foreach($assessments as $assessment)<tr><td><strong>{{ $assessment->title }}</strong><span>{{ $assessment->assessment_type }}</span></td><td>{{ $assessment->lpk->name }}</td><td>{{ $assessment->start_at->format('d M Y, H:i') }}</td><td><x-status :value="$assessment->expense ? $assessment->expense->status : 'BELUM_DILAPORKAN'" /></td><td><x-status :value="$assessment->status" /></td><td><a href="{{ route('assessments.show',$assessment) }}">Detail</a></td></tr>@endforeach</tbody></table></div>{{ $assessments->links() }}@else<div class="empty">{{ $search || $lpkId || $assessmentType || $status || $startFrom || $startTo ? 'Tidak ada program asesmen yang cocok dengan filter.' : 'Belum ada program asesmen.' }} @if($search || $lpkId || $assessmentType || $status || $startFrom || $startTo)<a class="button ghost empty-action" href="{{ route('assessments.index') }}">Reset filter</a>@endif</div>@endif
</section>
@endsection
