<!doctype html>
<html lang="id">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>@yield('title', 'SIMASADI Workspace')</title>@vite(['resources/css/app.css', 'resources/js/app.js'])</head>
<body>
<a class="skip-link" href="#main-content">Lewati ke konten</a>
<div class="app-shell">
<aside class="sidebar"><div class="brand"><span class="brand-mark">K</span><div><strong>SIMASADI</strong><small>workspace prototype</small></div></div><nav aria-label="Navigasi utama"><a href="{{ route('dashboard') }}" class="{{ request()->routeIs('dashboard') ? 'active' : '' }}">Ringkasan</a><a href="{{ route('monitoring.services') }}" class="{{ request()->routeIs('monitoring.services') ? 'active' : '' }}">Layanan KANMIS</a><a href="{{ route('monitoring.backups') }}" class="{{ request()->routeIs('monitoring.backups') ? 'active' : '' }}">Backup</a><a href="{{ route('calendar.index') }}" class="{{ request()->routeIs('calendar.*') ? 'active' : '' }}">Kalender</a><a href="{{ route('assessments.index') }}" class="{{ request()->routeIs('assessments.*') ? 'active' : '' }}">Program Asesmen</a><a href="{{ route('lpks.index') }}" class="{{ request()->routeIs('lpks.*') ? 'active' : '' }}">Data LPK</a><a href="{{ route('accreditations.index') }}" class="{{ request()->routeIs('accreditations.*') ? 'active' : '' }}">Akreditasi</a><a href="{{ route('issues.index') }}" class="{{ request()->routeIs('issues.*') ? 'active' : '' }}">Masalah</a><a href="{{ route('amendments.index') }}" class="{{ request()->routeIs('amendments.*') ? 'active' : '' }}">Amandemen</a></nav><div class="sidebar-foot"><span class="eyebrow">MODE BELAJAR</span><p>Data contoh lokal, belum terhubung ke sistem resmi.</p></div></aside>
 <main id="main-content" class="main-content"><header class="topbar"><div class="page-context"><span class="context-label">Monitoring internal</span><strong class="context-title">@php($pageTitle = match (true) { request()->routeIs('dashboard') => 'Ringkasan', request()->routeIs('monitoring.services') => 'Layanan KANMIS', request()->routeIs('monitoring.backups') => 'Riwayat Backup', request()->routeIs('calendar.*') => 'Kalender Kegiatan', request()->routeIs('assessments.*') => 'Program Asesmen', request()->routeIs('lpks.*') => 'Data LPK', request()->routeIs('accreditations.*') => 'Proses Akreditasi', request()->routeIs('issues.*') => 'Masalah', request()->routeIs('amendments.*') => 'Amandemen', default => 'Workspace' }){{ $pageTitle }}</strong></div><div class="user-menu"><div class="user-identity"><span class="user-avatar" aria-hidden="true">{{ collect(explode(' ', auth()->user()->name ?? 'Tamu'))->map(fn ($part) => substr($part, 0, 1))->take(2)->implode('') }}</span><div><strong>{{ auth()->user()->name ?? 'Tamu' }}</strong><small>Petugas monitoring</small></div></div><form method="POST" action="{{ route('logout') }}">@csrf<button type="submit" class="link-button"><x-icon name="log-out" size="16" /> Keluar</button></form></div></header><div class="page-wrap">@if(session('success'))<div class="alert success" role="status">{{ session('success') }}</div>@endif @if($errors->any())<div class="alert error" role="alert"><strong>Periksa kembali input.</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif @yield('content')</div></main>
</div>
</body></html>
